"""empty message

Revision ID: 61377214e4c4
Revises: bdab7f1170da
Create Date: 2021-06-02 17:57:37.399818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61377214e4c4'
down_revision = 'bdab7f1170da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_outfit',
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfit.id'], ),
    sa.PrimaryKeyConstraint('outfit_id', 'collection_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_outfit')
    # ### end Alembic commands ###
