"""empty message

Revision ID: 69e1b875b99f
Revises: 9e0630661dcb
Create Date: 2021-06-02 10:51:46.293198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e1b875b99f'
down_revision = '9e0630661dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('collection_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'collection', 'user', ['collection_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.drop_column('collection', 'collection_user_id')
    # ### end Alembic commands ###
