"""empty message

Revision ID: 76e5634d79dc
Revises: 0d9254b608ec
Create Date: 2021-06-04 18:44:23.996374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e5634d79dc'
down_revision = '0d9254b608ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clothing', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_constraint('clothing_clean_key', 'clothing', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('clothing_clean_key', 'clothing', ['clean'])
    op.alter_column('clothing', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
