"""empty message

Revision ID: dad114803e51
Revises: 4f8b6ccc5b68
Create Date: 2021-09-10 10:57:04.508817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad114803e51'
down_revision = '4f8b6ccc5b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing', sa.Column('dirty', sa.Boolean(), nullable=False))
    op.drop_column('clothing', 'clean')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing', sa.Column('clean', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('clothing', 'dirty')
    # ### end Alembic commands ###
